### ISSUE TITLE
Compile error!

### ISSUE THREAD

**Issue by lixy-toone** [opensourceBIM/IfcPlugins#4]
I cannot find the class "org.bimserver.shared.ListCapableVirtualObject" and Shared 1.5.78 SNAPSHOT.
Could you commit it ?

![2](https://user-images.githubusercontent.com/28996034/27027118-c11a032e-4f92-11e7-9b00-f51744a6a5c2.png)

![1](https://user-images.githubusercontent.com/28996034/27027164-e838fd70-4f92-11e7-8624-c3a7c1774f47.png)

**Comment by rubendel** [comment]
It is committed: https://github.com/opensourceBIM/BIMserver/blob/9a86d52737fda087d503cf48a13f14df2987332a/PluginBase/src/org/bimserver/shared/ListCapableVirtualObject.java
